name: firedart
description: An incomplete, dart-native implementation of the Firebase SDK.
version: 0.6.1
author: Daniel Cachapa <cachapa@gmail.com>
homepage: https://github.com/cachapa/firedart

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.12.0+2
  grpc: ^1.0.3 # Flutter is currently incompatible with version 2.x
  protobuf: ^0.13.15
  fixnum: ^0.10.9

dev_dependencies:
  test: ^1.6.4
