name: Code style

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
      - name: Verify code formatting
        run: dart format --set-exit-if-changed .
